/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PakOwnerNameRouteImport } from './routes/pak/$owner.$name'
import { Route as ApiSitemapXmlRouteImport } from './routes/api/sitemap.xml'
import { Route as ApiOgOwnerNamePngRouteImport } from './routes/api/og.$owner.$name.png'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PakOwnerNameRoute = PakOwnerNameRouteImport.update({
  id: '/pak/$owner/$name',
  path: '/pak/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapXmlRoute = ApiSitemapXmlRouteImport.update({
  id: '/api/sitemap/xml',
  path: '/api/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgOwnerNamePngRoute = ApiOgOwnerNamePngRouteImport.update({
  id: '/api/og/$owner/$name/png',
  path: '/api/og/$owner/$name/png',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/pak/$owner/$name': typeof PakOwnerNameRoute
  '/api/og/$owner/$name/png': typeof ApiOgOwnerNamePngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/pak/$owner/$name': typeof PakOwnerNameRoute
  '/api/og/$owner/$name/png': typeof ApiOgOwnerNamePngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/pak/$owner/$name': typeof PakOwnerNameRoute
  '/api/og/$owner/$name/png': typeof ApiOgOwnerNamePngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/trending'
    | '/api/sitemap/xml'
    | '/pak/$owner/$name'
    | '/api/og/$owner/$name/png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/trending'
    | '/api/sitemap/xml'
    | '/pak/$owner/$name'
    | '/api/og/$owner/$name/png'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/trending'
    | '/api/sitemap/xml'
    | '/pak/$owner/$name'
    | '/api/og/$owner/$name/png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  TrendingRoute: typeof TrendingRoute
  ApiSitemapXmlRoute: typeof ApiSitemapXmlRoute
  PakOwnerNameRoute: typeof PakOwnerNameRoute
  ApiOgOwnerNamePngRoute: typeof ApiOgOwnerNamePngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pak/$owner/$name': {
      id: '/pak/$owner/$name'
      path: '/pak/$owner/$name'
      fullPath: '/pak/$owner/$name'
      preLoaderRoute: typeof PakOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/xml': {
      id: '/api/sitemap/xml'
      path: '/api/sitemap/xml'
      fullPath: '/api/sitemap/xml'
      preLoaderRoute: typeof ApiSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$owner/$name/png': {
      id: '/api/og/$owner/$name/png'
      path: '/api/og/$owner/$name/png'
      fullPath: '/api/og/$owner/$name/png'
      preLoaderRoute: typeof ApiOgOwnerNamePngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  TrendingRoute: TrendingRoute,
  ApiSitemapXmlRoute: ApiSitemapXmlRoute,
  PakOwnerNameRoute: PakOwnerNameRoute,
  ApiOgOwnerNamePngRoute: ApiOgOwnerNamePngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
