/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Type of content item
 */
export type ContentItemType = 'file' | 'dir';
/**
 * Pak visibility level
 */
export type PakVisibility = 'PUBLIC' | 'UNLISTED' | 'PRIVATE';
/**
 * Sort order for listing paks
 */
export type PakSortBy = 'TRENDING' | 'MOST_POPULAR' | 'RECENT';
/**
 * Time window for download/usage counts
 */
export type PakTimeWindow = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'ALL_TIME';
/**
 * Pak version review status
 */
export type PakVersionStatus = 'SUBMITTED' | 'APPROVED' | 'REJECTED';
/**
 * Pak status
 */
export type PakStatus = 'ACTIVE' | 'DEPRECATED';
/**
 * Content of a pak - either a file or directory
 */
export type PakContent =
  | {
      /**
       * The file content
       */
      content: string;
      type: 'File';
    }
  | {
      /**
       * Directory contents
       */
      items: ContentItem[];
      type: 'Directory';
    };

/**
 * Root schema containing all API types Used for JSON Schema generation
 */
export interface PaksApiSchema {
  content_item: ContentItem;
  content_item_type: ContentItemType;
  error_detail: ErrorDetail;
  error_response: ErrorResponse;
  install_pak_info: InstallPakInfo;
  install_path_info: InstallPathInfo;
  install_repository_info: InstallRepositoryInfo;
  install_version_info: InstallVersionInfo;
  list_paks_query: ListPaksQuery;
  list_paks_response: ListPaksResponse;
  pak: Pak;
  pak_content: PakContent;
  pak_content_response: PakContentResponse;
  pak_install_response: PakInstallResponse;
  pak_sort_by: PakSortBy;
  pak_status: PakStatus;
  pak_time_window: PakTimeWindow;
  pak_version: PakVersion;
  pak_version_status: PakVersionStatus;
  pak_version_with_pak_and_path: PakVersionWithPakAndPath;
  pak_visibility: PakVisibility;
  pak_with_latest_version: PakWithLatestVersion;
  publish_pak_request: PublishPakRequest;
  publish_pak_response: PublishPakResponse;
  search_paks_query: SearchPaksQuery;
  search_paks_response: SearchPaksResponse;
  user_info: UserInfo;
  verify_token_response: VerifyTokenResponse;
}
/**
 * Content item in a directory listing
 */
export interface ContentItem {
  /**
   * File content (if pre-fetched)
   */
  content?: string | null;
  /**
   * File or directory name
   */
  name: string;
  /**
   * Size in bytes (for files)
   */
  size?: number | null;
  /**
   * Type of item
   */
  type: ContentItemType;
  /**
   * Full URI to this item
   */
  uri: string;
}
/**
 * Error detail
 */
export interface ErrorDetail {
  /**
   * Error code
   */
  code?: string | null;
  /**
   * Error message
   */
  message: string;
}
/**
 * API error response
 */
export interface ErrorResponse {
  /**
   * Error details
   */
  error: ErrorDetail;
}
/**
 * Pak info for installation
 */
export interface InstallPakInfo {
  /**
   * Pak description
   */
  description?: string | null;
  /**
   * Unique pak identifier
   */
  id: string;
  /**
   * Pak name
   */
  name: string;
  /**
   * Owner/account name
   */
  owner: string;
  /**
   * Visibility level
   */
  visibility: PakVisibility;
}
/**
 * Install path info
 */
export interface InstallPathInfo {
  /**
   * List of files/directories in the pak
   */
  files: string[];
  /**
   * Path within repo (for monorepos), "." for root
   */
  path: string;
}
/**
 * Repository info for installation
 */
export interface InstallRepositoryInfo {
  /**
   * HTTPS clone URL
   */
  clone_url: string;
  /**
   * Default branch name
   */
  default_branch: string;
  /**
   * SSH clone URL
   */
  ssh_url: string;
  /**
   * Repository URL
   */
  url: string;
}
/**
 * Version info for installation
 */
export interface InstallVersionInfo {
  /**
   * Full commit SHA
   */
  commit_hash: string;
  /**
   * Publication timestamp
   */
  published_at: string;
  /**
   * Git tag (e.g., v1.2.3)
   */
  tag: string;
  /**
   * Semantic version (e.g., 1.2.3)
   */
  version: string;
}
/**
 * Query parameters for listing paks
 */
export interface ListPaksQuery {
  /**
   * Maximum number of results
   */
  limit?: number | null;
  /**
   * Pagination offset
   */
  offset?: number | null;
  /**
   * Sort order: TRENDING, MOST_POPULAR, or RECENT
   */
  sort_by?: PakSortBy | null;
  /**
   * Time window for download counts
   */
  time_window?: PakTimeWindow | null;
}
/**
 * Response from listing paks
 */
export interface ListPaksResponse {
  /**
   * List of paks with their latest versions
   */
  results: PakWithLatestVersion[];
}
/**
 * Pak with its latest version info
 */
export interface PakWithLatestVersion {
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Pak description
   */
  description?: string | null;
  /**
   * Downloads in current time window
   */
  download_count: number;
  /**
   * Full URI with protocol (stakpak://owner/name)
   */
  full_uri: string;
  /**
   * Unique identifier
   */
  id: string;
  /**
   * Latest version info (null if no versions)
   */
  latest_version?: PakVersion | null;
  /**
   * Pak name
   */
  name: string;
  /**
   * Owner/account name
   */
  owner_name: string;
  /**
   * Path within repository (for monorepos)
   */
  path?: string | null;
  /**
   * Git repository URL
   */
  repository_url: string;
  /**
   * Status
   */
  status: PakStatus;
  /**
   * Tags/keywords
   */
  tags: string[];
  /**
   * Total downloads all time
   */
  total_downloads: number;
  /**
   * Total usages all time
   */
  total_usages: number;
  /**
   * Last update timestamp
   */
  updated_at: string;
  /**
   * Short URI (owner/name)
   */
  uri: string;
  /**
   * Usages in current time window
   */
  usage_count: number;
  /**
   * Visibility level
   */
  visibility: PakVisibility;
}
/**
 * A specific version of a pak
 */
export interface PakVersion {
  /**
   * Content checksum
   */
  checksum: string;
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Download count for this version
   */
  downloads: number;
  /**
   * Git tag (e.g., v1.0.0)
   */
  git_tag: string;
  /**
   * Unique identifier
   */
  id: string;
  /**
   * pak.toml manifest content
   */
  manifest: string;
  /**
   * Publication timestamp
   */
  published_at: string;
  /**
   * Size in bytes
   */
  size_bytes?: number | null;
  /**
   * Review status
   */
  status: PakVersionStatus;
  /**
   * Last update timestamp
   */
  updated_at: string;
  /**
   * Usage count for this version
   */
  usages: number;
  /**
   * Semantic version (e.g., 1.0.0)
   */
  version: string;
}
/**
 * A pak (knowledge package) in the registry
 */
export interface Pak {
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Pak description
   */
  description?: string | null;
  /**
   * Downloads in current time window
   */
  download_count: number;
  /**
   * Full URI with protocol (stakpak://owner/name)
   */
  full_uri: string;
  /**
   * Unique identifier
   */
  id: string;
  /**
   * Pak name
   */
  name: string;
  /**
   * Owner/account name
   */
  owner_name: string;
  /**
   * Path within repository (for monorepos)
   */
  path?: string | null;
  /**
   * Git repository URL
   */
  repository_url: string;
  /**
   * Status
   */
  status: PakStatus;
  /**
   * Tags/keywords
   */
  tags: string[];
  /**
   * Total downloads all time
   */
  total_downloads: number;
  /**
   * Total usages all time
   */
  total_usages: number;
  /**
   * Last update timestamp
   */
  updated_at: string;
  /**
   * Short URI (owner/name)
   */
  uri: string;
  /**
   * Usages in current time window
   */
  usage_count: number;
  /**
   * Visibility level
   */
  visibility: PakVisibility;
}
/**
 * Response from the content endpoint
 */
export interface PakContentResponse {
  /**
   * Content (file or directory)
   */
  content: PakContent;
  /**
   * Requested URI
   */
  uri: string;
}
/**
 * Response from the install endpoint
 */
export interface PakInstallResponse {
  /**
   * Installation path info
   */
  install: InstallPathInfo;
  /**
   * Pak information
   */
  pak: InstallPakInfo;
  /**
   * Repository information
   */
  repository: InstallRepositoryInfo;
  /**
   * Version information
   */
  version: InstallVersionInfo;
}
/**
 * Pak version with full pak info and optional path
 */
export interface PakVersionWithPakAndPath {
  /**
   * Content checksum
   */
  checksum: string;
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Download count
   */
  downloads: number;
  /**
   * Git tag
   */
  git_tag: string;
  /**
   * Unique identifier
   */
  id: string;
  /**
   * pak.toml manifest content
   */
  manifest: string;
  /**
   * The pak
   */
  pak: Pak;
  /**
   * Requested path within pak
   */
  path?: string | null;
  /**
   * Publication timestamp
   */
  published_at: string;
  /**
   * Size in bytes
   */
  size_bytes?: number | null;
  /**
   * Review status
   */
  status: PakVersionStatus;
  /**
   * Last update timestamp
   */
  updated_at: string;
  /**
   * Usage count
   */
  usages: number;
  /**
   * Semantic version
   */
  version: string;
}
/**
 * Request body for POST /v1/paks/publish
 */
export interface PublishPakRequest {
  /**
   * Branch the tag was created from
   */
  branch: string;
  /**
   * Path to pak within repo ("." for root, "paks/my-pak" for monorepo)
   */
  path?: string | null;
  /**
   * Git clone URL (HTTPS) - must be a GitHub URL
   */
  repository: string;
  /**
   * Git tag name (must start with `v` and follow semver)
   */
  tag: string;
}
/**
 * Response from publish endpoint (empty on success - 200 OK)
 */
export interface PublishPakResponse {}
/**
 * Query parameters for searching paks
 */
export interface SearchPaksQuery {
  /**
   * Maximum number of results
   */
  limit?: number | null;
  /**
   * Pagination offset
   */
  offset?: number | null;
  /**
   * Owner name (for identifier search)
   */
  owner?: string | null;
  /**
   * Pak name (for identifier search)
   */
  pak_name?: string | null;
  /**
   * Freeform keyword query
   */
  query?: string | null;
}
/**
 * Response from searching paks
 */
export interface SearchPaksResponse {
  /**
   * List of matching paks
   */
  results: Pak[];
}
/**
 * User information returned from auth endpoints
 */
export interface UserInfo {
  /**
   * Company
   */
  company?: string | null;
  /**
   * Email address
   */
  email: string;
  /**
   * First name
   */
  first_name?: string | null;
  /**
   * User ID
   */
  id: string;
  /**
   * Job role
   */
  job_role?: string | null;
  /**
   * Last name
   */
  last_name?: string | null;
  /**
   * Profile image URL
   */
  profile_img_url?: string | null;
  /**
   * Username
   */
  username: string;
}
/**
 * Response from token verification
 */
export interface VerifyTokenResponse {
  /**
   * Token expiration time (null if no expiry)
   */
  expires_at?: string | null;
  /**
   * User info
   */
  user: UserInfo;
  /**
   * Whether the token is valid
   */
  valid: boolean;
}
